/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/model/portfolio.gltf -t -k 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_64: THREE.SkinnedMesh
    Object_66: THREE.SkinnedMesh
    Object_68: THREE.SkinnedMesh
    Plane_Material004_0: THREE.Mesh
    Plane001_Material004_0: THREE.Mesh
    Plane002_Material004_0: THREE.Mesh
    Plane003_Material004_0: THREE.Mesh
    ['��������_��������_0']: THREE.Mesh
    ['����������_Material005_0']: THREE.Mesh
    Cylinder_Material001_0: THREE.Mesh
    Cylinder_Material002_0: THREE.Mesh
    Plane016_Material005_0: THREE.Mesh
    Plane016_Material006_0: THREE.Mesh
    Plane016_Material007_0: THREE.Mesh
    Plane016_Material008_0: THREE.Mesh
    Plane016_Material009_0: THREE.Mesh
    Plane016_Material010_0: THREE.Mesh
    Plane016_Material011_0: THREE.Mesh
    Plane016_Material012_0: THREE.Mesh
    Plane016_Material013_0: THREE.Mesh
    Plane016_Material014_0: THREE.Mesh
    Plane016_Material015_0: THREE.Mesh
    Plane016_Material016_0: THREE.Mesh
    Plane016_Material017_0: THREE.Mesh
    Plane016_Material018_0: THREE.Mesh
    Plane016_Material019_0: THREE.Mesh
    Plane016_Material020_0: THREE.Mesh
    Plane016_Material021_0: THREE.Mesh
    Plane016_Material022_0: THREE.Mesh
    Plane016_Material023_0: THREE.Mesh
    Plane016_Material024_0: THREE.Mesh
    Plane016_Material025_0: THREE.Mesh
    Cube012: THREE.Mesh
    Cube064: THREE.Mesh
    Cube064_1: THREE.Mesh
    Cube065: THREE.Mesh
    Cube065_1: THREE.Mesh
    Cube065_2: THREE.Mesh
    Cube066: THREE.Mesh
    Cube066_1: THREE.Mesh
    Cube066_2: THREE.Mesh
    Cube067: THREE.Mesh
    Cube067_1: THREE.Mesh
    Cube067_2: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cube069: THREE.Mesh
    Cube069_1: THREE.Mesh
    Cube070: THREE.Mesh
    Cube070_1: THREE.Mesh
    Cube070_2: THREE.Mesh
    Cylinder004: THREE.Mesh
    keyboard: THREE.Mesh
    Cube057: THREE.Mesh
    Cube057_1: THREE.Mesh
    Cube057_2: THREE.Mesh
    _rootJoint: THREE.Bone
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.022']: THREE.MeshStandardMaterial
    ['Material.023']: THREE.MeshStandardMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    table: THREE.MeshStandardMaterial
    black: THREE.MeshStandardMaterial
    black_glossy: THREE.MeshStandardMaterial
    bottom: THREE.MeshStandardMaterial
    metal: THREE.MeshStandardMaterial
    orange: THREE.MeshStandardMaterial
    phone: THREE.MeshStandardMaterial
    blueEmis: THREE.MeshStandardMaterial
    ['black.002']: THREE.MeshStandardMaterial
    greenEmis: THREE.MeshStandardMaterial
    screen: THREE.MeshStandardMaterial
  }
}

type ActionName = 'Poses'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['skinnedMesh'] | JSX.IntrinsicElements['mesh'] | JSX.IntrinsicElements['bone']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials, animations } = useGLTF('/model/portfolio.gltf') as GLTFResult
  const { actions } = useAnimations<GLTFActions>(animations, group)
  return (
    <group ref={group} {...props} dispose={null} castShadow>
      <group name="Scene">
        <group name="Sketchfab_model" position={[-0.036, 1.157, 0.566]} rotation={[-Math.PI / 2, 0, 3.042]} scale={0.105}>
          <group name="0d8ec9da64704eac91fe821decc63238fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Abel">
                  <group name="Object_5">
                    <group name="Object_63" rotation={[-Math.PI / 2, 0, 0]} />
                    <group name="Object_65" rotation={[-Math.PI / 2, 0, 0]} />
                    <group name="Object_67" rotation={[-Math.PI / 2, 0, 0]} />
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials['Material.002']} skeleton={nodes.Object_64.skeleton} />
                    <skinnedMesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials['Material.002']} skeleton={nodes.Object_66.skeleton} />
                    <skinnedMesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials['Material.002']} skeleton={nodes.Object_68.skeleton} />
                  </group>
                </group>
                <group name="Body" rotation={[-Math.PI / 2, 0, 0]} />
                <group name="Clothes" rotation={[-Math.PI / 2, 0, 0]} />
                <group name="Hairs" rotation={[-Math.PI / 2, 0, 0]} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model001" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="93c4c44aadb449e58037622dda9c5919objcleanermaterialmergergle" />
        </group>
        <group name="Sketchfab_model002" position={[0.574, 0.792, -0.055]} rotation={[-Math.PI / 2, 0, 0]} scale={0.055}>
          <group name="cat_on_cupfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode001">
              <group name="Plane" position={[0, 144.618, 54.842]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Plane_Material004_0" geometry={nodes.Plane_Material004_0.geometry} material={materials['Material.004']} />
              </group>
              <group name="Plane001" position={[0, 134.673, 69.346]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Plane001_Material004_0" geometry={nodes.Plane001_Material004_0.geometry} material={materials['Material.004']} />
              </group>
              <group name="Plane002" position={[0, 131.116, 72.197]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="Plane002_Material004_0" geometry={nodes.Plane002_Material004_0.geometry} material={materials['Material.004']} />
              </group>
              <group name="Plane003" position={[0, 127.834, 69.346]} rotation={[-Math.PI / 2, 0, 0]} scale={62.341}>
                <mesh name="Plane003_Material004_0" geometry={nodes.Plane003_Material004_0.geometry} material={materials['Material.004']} />
              </group>
              <group name="��������" position={[0, 100, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="��������_��������_0" geometry={nodes['��������_��������_0'].geometry} material={materials.material} />
              </group>
              <group name="����������" position={[0, 100, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh name="����������_Material005_0" geometry={nodes['����������_Material005_0'].geometry} material={materials['Material.005']} />
              </group>
            </group>
          </group>
        </group>
        <group name="Sketchfab_model003" position={[-0.686, 0.835, -0.135]} rotation={[-Math.PI / 2, 0, 0]} scale={0.061}>
          <group name="Plantsfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="RootNode002">
              <group name="Cylinder" rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 67.883]}>
                <mesh name="Cylinder_Material001_0" geometry={nodes.Cylinder_Material001_0.geometry} material={materials['Material.003']} />
                <mesh name="Cylinder_Material002_0" geometry={nodes.Cylinder_Material002_0.geometry} material={materials['Material.006']} />
              </group>
              <group name="Plane016" position={[-3.42, 114.513, 21.543]} rotation={[-1.939, 0.591, -0.905]} scale={[51.466, 76.679, 76.896]}>
                <mesh name="Plane016_Material005_0" geometry={nodes.Plane016_Material005_0.geometry} material={materials['Material.007']} />
                <mesh name="Plane016_Material006_0" geometry={nodes.Plane016_Material006_0.geometry} material={materials['Material.008']} />
                <mesh name="Plane016_Material007_0" geometry={nodes.Plane016_Material007_0.geometry} material={materials['Material.009']} />
                <mesh name="Plane016_Material008_0" geometry={nodes.Plane016_Material008_0.geometry} material={materials['Material.010']} />
                <mesh name="Plane016_Material009_0" geometry={nodes.Plane016_Material009_0.geometry} material={materials['Material.011']} />
                <mesh name="Plane016_Material010_0" geometry={nodes.Plane016_Material010_0.geometry} material={materials['Material.012']} />
                <mesh name="Plane016_Material011_0" geometry={nodes.Plane016_Material011_0.geometry} material={materials['Material.013']} />
                <mesh name="Plane016_Material012_0" geometry={nodes.Plane016_Material012_0.geometry} material={materials['Material.014']} />
                <mesh name="Plane016_Material013_0" geometry={nodes.Plane016_Material013_0.geometry} material={materials['Material.015']} />
                <mesh name="Plane016_Material014_0" geometry={nodes.Plane016_Material014_0.geometry} material={materials['Material.016']} />
                <mesh name="Plane016_Material015_0" geometry={nodes.Plane016_Material015_0.geometry} material={materials['Material.017']} />
                <mesh name="Plane016_Material016_0" geometry={nodes.Plane016_Material016_0.geometry} material={materials['Material.018']} />
                <mesh name="Plane016_Material017_0" geometry={nodes.Plane016_Material017_0.geometry} material={materials['Material.019']} />
                <mesh name="Plane016_Material018_0" geometry={nodes.Plane016_Material018_0.geometry} material={materials['Material.020']} />
                <mesh name="Plane016_Material019_0" geometry={nodes.Plane016_Material019_0.geometry} material={materials['Material.022']} />
                <mesh name="Plane016_Material020_0" geometry={nodes.Plane016_Material020_0.geometry} material={materials['Material.023']} />
                <mesh name="Plane016_Material021_0" geometry={nodes.Plane016_Material021_0.geometry} material={materials['Material.021']} />
                <mesh name="Plane016_Material022_0" geometry={nodes.Plane016_Material022_0.geometry} material={materials['Material.024']} />
                <mesh name="Plane016_Material023_0" geometry={nodes.Plane016_Material023_0.geometry} material={materials['Material.025']} />
                <mesh name="Plane016_Material024_0" geometry={nodes.Plane016_Material024_0.geometry} material={materials['Material.026']} />
                <mesh name="Plane016_Material025_0" geometry={nodes.Plane016_Material025_0.geometry} material={materials['Material.027']} />
              </group>
            </group>
          </group>
        </group>
        <mesh name="Cube012" geometry={nodes.Cube012.geometry} material={materials.table} position={[0, 0.662, -0.489]} rotation={[Math.PI / 2, 0, 0]} scale={0.32} />
        <group name="Cube013" position={[-0.529, 0.915, -0.481]} rotation={[0, 0.384, 0]} scale={0.32}>
          <mesh name="Cube064" geometry={nodes.Cube064.geometry} material={materials.black} />
          <mesh name="Cube064_1" geometry={nodes.Cube064_1.geometry} material={materials.black_glossy} />
        </group>
        <group name="Cube010" position={[-0.556, 1.041, -0.476]} scale={0.32}>
          <mesh name="Cube065" geometry={nodes.Cube065.geometry} material={materials.bottom} />
          <mesh name="Cube065_1" geometry={nodes.Cube065_1.geometry} material={materials.metal} />
          <mesh name="Cube065_2" geometry={nodes.Cube065_2.geometry} material={materials.black} />
        </group>
        <group name="Cube011" position={[-0.545, 1.045, -0.5]} rotation={[-2.22, -1.565, -2.044]} scale={0.32}>
          <mesh name="Cube066" geometry={nodes.Cube066.geometry} material={materials.orange} />
          <mesh name="Cube066_1" geometry={nodes.Cube066_1.geometry} material={materials.metal} />
          <mesh name="Cube066_2" geometry={nodes.Cube066_2.geometry} material={materials.black} />
        </group>
        <group name="Cube014" position={[-0.483, 1.041, -0.457]} rotation={[0, 0.577, -Math.PI]} scale={0.32}>
          <mesh name="Cube067" geometry={nodes.Cube067.geometry} material={materials.phone} />
          <mesh name="Cube067_1" geometry={nodes.Cube067_1.geometry} material={materials.metal} />
          <mesh name="Cube067_2" geometry={nodes.Cube067_2.geometry} material={materials.black} />
        </group>
        <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials.black} position={[0.543, 0.824, -0.314]} scale={0.32} />
        <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials.black} position={[0.543, 0.815, -0.314]} rotation={[0, 0, -0.046]} scale={0.32} />
        <group name="Cube016" position={[0, 0.811, -0.451]} rotation={[0, -0.301, 0]} scale={0.32}>
          <mesh name="Cube069" geometry={nodes.Cube069.geometry} material={materials.phone} />
          <mesh name="Cube069_1" geometry={nodes.Cube069_1.geometry} material={materials.black_glossy} />
        </group>
        <group name="Cube017" position={[0.742, 0.98, -0.489]} scale={0.32}>
          <mesh name="Cube070" geometry={nodes.Cube070.geometry} material={materials.black} />
          <mesh name="Cube070_1" geometry={nodes.Cube070_1.geometry} material={materials.blueEmis} />
          <mesh name="Cube070_2" geometry={nodes.Cube070_2.geometry} material={materials.black_glossy} />
        </group>
        <mesh name="Cylinder004" geometry={nodes.Cylinder004.geometry} material={materials['black.002']} position={[0.702, 1.061, -0.235]} rotation={[Math.PI / 2, 0, 0]} scale={0.006} />
        <mesh name="keyboard" geometry={nodes.keyboard.geometry} material={materials.black} position={[-0.058, 0.808, -0.254]} rotation={[0.164, 0.111, -0.018]} scale={0.32} />
        <group name="monitor" position={[0.006, 1.109, -0.483]} scale={0.32}>
          <mesh name="Cube057" geometry={nodes.Cube057.geometry} material={materials.black} />
          <mesh name="Cube057_1" geometry={nodes.Cube057_1.geometry} material={materials.greenEmis} />
          <mesh name="Cube057_2" geometry={nodes.Cube057_2.geometry} material={materials.screen} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model/portfolio.gltf')
